requires:
- impls/my_unsafe_stack
- impls/my_sync_stack
- impls/my_lock
- impls/scal_object

implementations:
- id: mystack
  name: My Synchronized Stack
  class: MySyncStack
  args: []

- id: unsafestack
  name: My Unsafe Stack
  class: MyUnsafeStack
  args: []

- id: mylock
  name: My Lock
  class: MyLock
  args: []

- id: bkq
  name: Bounded-Size k-FIFO (Scal)
  class: ScalObject
  args: [bkq]

- id: dq
  name: Distributed Queue (Scal)
  class: ScalObject
  args: [dq]

- id: dtsq
  name: Distributed Time-Stamped Queue (Scal)
  class: ScalObject
  args: [dtsq]

- id: lbq
  name: Load-Balancing Queue (Scal)
  class: ScalObject
  args: [lbq]

- id: msq
  name: Michael-Scott Queue (Scal)
  class: ScalObject
  args: [msq]

- id: fcq
  name: Flat-Combining Queue (Scal)
  class: ScalObject
  args: [fcq]

- id: ks
  name: ??? Stack (Scal)
  class: ScalObject
  args: [ks]

- id: rdq
  name: Random-Dequeue Queue (Scal)
  class: ScalObject
  args: [rdq]

- id: sl
  name: Singly-Linked List (Scal)
  class: ScalObject
  args: [sl]

- id: ts
  name: Trieber Stack (Scal)
  class: ScalObject
  args: [ts]

- id: tsd
  name: Time-Stamped Dequeue (Scal)
  class: ScalObject
  args: [tsd]

- id: tsq
  name: Time-Stamped Queue (Scal)
  class: ScalObject
  args: [tsq]

- id: tss
  name: Time-Stamped Stack (Scal)
  class: ScalObject
  args: [tss]

- id: ukq
  name: Unbounded-Size k-FIFO (Scal)
  class: ScalObject
  args: [ukq]

- id: wfq11
  name: Wait-Free Queue ’11 (Scal)
  class: ScalObject
  args: [wfq11]

- id: wfq12
  name: Wait-Free Queue ’12 (Scal)
  class: ScalObject
  args: [wfq12]
